services:
  # general settings
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Antwerpes\Typo3Docchecklogin\:
    resource: '../Classes/*'

  Antwerpes\Typo3Docchecklogin\Services\DocCheckAuthenticationService:
    arguments:
      - '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
      - '@TYPO3\CMS\Core\TypoScript\TypoScriptService'
      - '@TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer'
    public: true
